language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2/

env:
  global:
    # SONATYPE_USERNAME
    - secure: "pUhrrWSmZ9Lqd7KwEgyzVTr3b1BGKLMj9T0vwLrjMv09YO8P5AzDkJjJNpu8Z5M9j8I1NqwLyREXXq5RJzf9xTw/iq44O8szbPQJDSXnQWDURrwSTFqdmioK4c0jibsYB1Yd/K4QVfNcpqgEKfz404KgmZI4T8GbH9ZTWjFwdzgBNV9LOUOlBbBskr3u1kmQOz0e+5VENOjKXP6BpC2rEsV+Q2rVug3ga7LU32DRo+iRNrGxDleG7rPmXyEB8esbMalOIYV5hWxyJkQ/IDS2z1xKQ3SiLxrzDm0HDiTUckU36Q21JUJ9bXXWapBbdFzBWq+fXTsZhWoW6kzbgZG8CzrveDfabcJJ1yj4zGc5X1RSkYNHaH647bamkeSnpnsBg46VkJ6UdNBh95HUQMksJq4kPQbRc1mgpxcmF1B1OMT25mA2pS6EzwrU/yfPOvN21lavf/sRAXRbKELW01d6j56hg/1dB0m3gtGOyj8Itdlp+uJPn/kIcbihefEeHR37cYZ1IgEa/N2Ym4KX8pL7vDecoQaq7UzxVmHCxi6GBcPRWbfUPS7eWwYwoU+iR7UWZ2oeW9pwkG7IEo45UVAeIz0GcpF/15TxFIHk+DV18VgJBm6tCJonAQsXnB3JQOCYDviAV5SjIjMoFE0V8Q0JpPrXAVz42ldFo0OWv/ZBVEI="
    # SONATYPE_PASSWORD
    - secure: "YFK5DqBynWxe2KlO4aO9swaFHMMHuA2DalX4t6EnNtYipGGZWIJJLbBdBR1HktiRlCGj1zIyVJbGUzG4BQGBjXoAXNV+eDigCqxHdvcuNYQMJ2kOvzQyzk6L/6e8Wu/PUAkA4qhNRg0qSeAnonkjzJmsHRwyTljHa/YMTfcnTtsfWgngCzPFXiJznyqSKFs/kgo7fexXABEpNs91ANt6434eTuVUn+f35+FZQAa6MuEjhxsO6wTxMufb2wTpl0b/q1rYPO3uhQJMxF/554wnZuuiGdVnD4EunQif0ouAHCq9IyCNfV2vPlE44iD1WLXsI5F1cYEG1BH9VDCI8WCJryIDYDf2DMboEkfNMLGrIjixUni2KygWJuZ7PvK3bcfqvYLuZfy6wUhZbQPW++pLntPpMHCoURVO1PiI52FdfeW0eotR3QcjSvvNjPEJhqlueK2saTA+uzl12KzeEA1oMcuGTGXiA5qftGdQS+sP7UMaS5nHNRMbbYM6JC59UgiqUGtBkeCv0tg4IS7PNkv2iaTvVpEy9Vy9VEH4J6qCmAcw00u2raaQLOl/kOE8ZrGghQiVnfU7RNCskPqa+h1pIFw86WVyyy1aAu/JnwewO9KLWnsfMCQPCxcgHN9VKr1F05Jdq6pIpSHJDt4sKGxDckOMve23iG6QFSrVlphNIRI="
    # GPG_KEY_NAME
    - secure: "FdJwtQSJa2425Sqyq2bUaROJ8AS7xMBtKyJl3Bl7JKTckmAB4fkLCZAy/HDwHCjIjtzzqzafdkea0GDALGi9KciH3jR8X5c5xLnK6dXRhJPWUsW/lx1LepFimOI6f2puMVUiv4zg7jEBkV7fWrwppDZGz5syYEL9JOtPAH1nW7VeMqmWoGEDJji7DTlcINBB844SXkr/XBELS77La9K/xM2VrT67s3oba2mpWBeHzCvZQCKhQFEw/GnOt3wtMPps5kgvhLPlwge/2tEkEgNO+cz/U2m2T7iS6sgLJ+azIpQjsJy4rRwZlH08TFRD/RMKXIBuBErVcEBnHt69YcBKN0FnttvS5eM/tt+7CXAW/O/w4uj1kbKnXKbeJeLdYdX2ervz22rtmflePLb4ldAo7cQfR08gnnV1jiJzBrlBKK36v5EjvZRj/5DXo/z7El0QO20Kki6xxjsKdTYZw2DURCVnKRKhk2KO3WkKnu+uEIhhzEEd9QeEJWiMJgSW6ntW0vTITaav9GW/kywYaWXskKhoi3FFwLMY9OEOWLWZtLfgvc7l9YMi5boWFNTP8PK6LMNj7AcbgzN7ER+4BTSIQVVaTUpPiFs+GCNQc3+yqb6meF0vDluZaG3WyB2159psvGh8TXovdbnDuHZhzyq4d88LGwhEmDR/3lXPsfN76Gw="
    # GPG_PASSPHRASE
    - secure: "VeSEC0xxEPh7H6hj4aEsyN8b7/nNNlZ3VzzO/fy9Ail2LxSfdouKL9v05zeNN2YvQsQx6suD1mb1PwQ3HxCH7Mkdg6yXxko7vu7CdIwDmrjWygVJEzzut84bqFLHAzQb6FPz51SiOLevkzLunR9asiUzmcZppxn6PSP6uSEk5xfxrHvsLt01JUUHyBkizz7Rp1R+WvFrlKoQ9L2moh1hKRWD5WwCTY3OJzq9Pag2Iw6XsCgoBlTTswiEErstHx4Y6K7DZhF2NppxUPckKkZwWC04WWYcSKgYEkxX+d5JAeZVBYQHERGt/zYfUERYc9XOhuV8tOIZPTOepWneCX0RdO1McuBwnWssvrmm5mZn1GdQ3SJEbaQJ3DumuXIiYKf5pMyg5FI+X41ehA5OTrdTQGrB+6E9krHon5jon2l+mtKAxbbPJkh490GL/tSpZ7CEKpEK0qUR+tEYZU/hK3MfBJaY7Rz/rCaZfiPifKvtFea3SX/XT3hNOOgX/qZ9KPNyuOZw20Pfv6GKvlIOp5E/Tl//F6PgVN0uWwnnGJCfskXJ9QRUpaQ7qO/i0Sca8UK5zmlyekWp+H5jxGLKnun+QaQzTuo4Ale4RCccMgbK5uQZ0C9QoGIioVOJB5AI2sTWewNXCltJAFv9os2It1jt9ansOkG8DMApG6AuMo6RUMg="

script:
  - mvn clean verify -Pcoverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./scripts/deploy.sh

branches:
  only:
    - master

notifications:
  email:
    - dbeam-dev+travis-notifications@spotify.com
